/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-23 06:15:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modaltest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("    display: none; /* Hidden by default */\r\n");
      out.write("    position: fixed; /* Stay in place */\r\n");
      out.write("    z-index: 1; /* Sit on top */\r\n");
      out.write("    padding-top: 100px; /* Location of the box */\r\n");
      out.write("    left: 0;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 100%; /* Full width */\r\n");
      out.write("    height: 100%; /* Full height */\r\n");
      out.write("    overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("    background-color: rgb(0,0,0); /* Fallback color */\r\n");
      out.write("    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content */\r\n");
      out.write(".modal-content {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    background-color: #fefefe;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    border: 1px solid #888;\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);\r\n");
      out.write("    -webkit-animation-name: animatetop;\r\n");
      out.write("    -webkit-animation-duration: 0.4s;\r\n");
      out.write("    animation-name: animatetop;\r\n");
      out.write("    animation-duration: 0.4s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add Animation */\r\n");
      out.write("@-webkit-keyframes animatetop {\r\n");
      out.write("    from {top:-300px; opacity:0} \r\n");
      out.write("    to {top:0; opacity:1}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes animatetop {\r\n");
      out.write("    from {top:-300px; opacity:0}\r\n");
      out.write("    to {top:0; opacity:1}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Close Button */\r\n");
      out.write(".close {\r\n");
      out.write("    color: white;\r\n");
      out.write("    float: right;\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover,\r\n");
      out.write(".close:focus {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-header {\r\n");
      out.write("    padding: 2px 16px;\r\n");
      out.write("    background-color: #5cb85c;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-body {padding: 2px 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-footer {\r\n");
      out.write("    padding: 2px 16px;\r\n");
      out.write("    background-color: #5cb85c;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Trigger/Open The Modal -->\r\n");
      out.write("<button id=\"myBtn\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "page0.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Trigger/Open The Modal -->\r\n");
      out.write("<button id=\"myBtn2\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal2\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Trigger/Open The Modal -->\r\n");
      out.write("<button id=\"myBtn3\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal3\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button id=\"myBtn4\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal4\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<button id=\"myBtn5\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal5\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button id=\"myBtn6\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal6\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button id=\"myBtn7\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal7\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button id=\"myBtn8\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal8\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button id=\"myBtn9\">Open Modal</button>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal9\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Modal Header</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <p>Some text in the Modal Body</p>\r\n");
      out.write("      <p>Some other text...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("      <h3>Modal Footer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("//Get the modal\r\n");
      out.write("var modal = document.getElementById('myModal');\r\n");
      out.write("var modal2 = document.getElementById('myModal2');\r\n");
      out.write("var modal3 = document.getElementById('myModal3');\r\n");
      out.write("var modal4 = document.getElementById('myModal4');\r\n");
      out.write("var modal5 = document.getElementById('myModal5');\r\n");
      out.write("var modal6 = document.getElementById('myModal6');\r\n");
      out.write("var modal7 = document.getElementById('myModal7');\r\n");
      out.write("var modal8 = document.getElementById('myModal8');\r\n");
      out.write("var modal9 = document.getElementById('myModal9');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Get the button that opens the modal\r\n");
      out.write("var btn = document.getElementById(\"myBtn\");\r\n");
      out.write("var btn2 = document.getElementById(\"myBtn2\");\r\n");
      out.write("var btn3 = document.getElementById(\"myBtn3\");\r\n");
      out.write("var btn4 = document.getElementById(\"myBtn4\");\r\n");
      out.write("var btn5 = document.getElementById(\"myBtn5\");\r\n");
      out.write("var btn6 = document.getElementById(\"myBtn6\");\r\n");
      out.write("var btn7 = document.getElementById(\"myBtn7\");\r\n");
      out.write("var btn8 = document.getElementById(\"myBtn8\");\r\n");
      out.write("var btn9 = document.getElementById(\"myBtn9\");\r\n");
      out.write("\r\n");
      out.write("// Get the <span> element that closes the modal\r\n");
      out.write("var span = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("var span2 = document.getElementsByClassName(\"close\")[1];\r\n");
      out.write("var span3 = document.getElementsByClassName(\"close\")[2];\r\n");
      out.write("var span4 = document.getElementsByClassName(\"close\")[3];\r\n");
      out.write("var span5 = document.getElementsByClassName(\"close\")[4];\r\n");
      out.write("var span6 = document.getElementsByClassName(\"close\")[5];\r\n");
      out.write("var span7 = document.getElementsByClassName(\"close\")[6];\r\n");
      out.write("var span8 = document.getElementsByClassName(\"close\")[7];\r\n");
      out.write("var span9 = document.getElementsByClassName(\"close\")[8];\r\n");
      out.write("\r\n");
      out.write("// When the user clicks the button, open the modal \r\n");
      out.write("btn.onclick = function() {\r\n");
      out.write("    modal.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn2.onclick = function() {\r\n");
      out.write("    modal2.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn3.onclick = function() {\r\n");
      out.write("    modal3.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn4.onclick = function() {\r\n");
      out.write("    modal4.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn5.onclick = function() {\r\n");
      out.write("    modal5.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn6.onclick = function() {\r\n");
      out.write("    modal6.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn7.onclick = function() {\r\n");
      out.write("    modal7.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn8.onclick = function() {\r\n");
      out.write("    modal8.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("btn9.onclick = function() {\r\n");
      out.write("    modal9.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// When the user clicks on <span> (x), close the modal\r\n");
      out.write("span.onclick = function() {\r\n");
      out.write("    modal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span2.onclick = function() {\r\n");
      out.write("    modal2.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span3.onclick = function() {\r\n");
      out.write("    modal3.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span4.onclick = function() {\r\n");
      out.write("    modal4.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span5.onclick = function() {\r\n");
      out.write("    modal5.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span6.onclick = function() {\r\n");
      out.write("    modal6.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span7.onclick = function() {\r\n");
      out.write("    modal7.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span8.onclick = function() {\r\n");
      out.write("    modal8.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("span9.onclick = function() {\r\n");
      out.write("    modal9.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("    if (event.target == modal) {\r\n");
      out.write("        modal.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event2) {\r\n");
      out.write("    if (event2.target == modal2) {\r\n");
      out.write("        modal2.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event3) {\r\n");
      out.write("    if (event3.target == modal3) {\r\n");
      out.write("        modal3.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event4) {\r\n");
      out.write("    if (event4.target == modal4) {\r\n");
      out.write("        modal4.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event5) {\r\n");
      out.write("    if (event5.target == modal5) {\r\n");
      out.write("        modal5.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event6) {\r\n");
      out.write("    if (event6.target == modal6) {\r\n");
      out.write("        modal6.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event7) {\r\n");
      out.write("    if (event7.target == modal7) {\r\n");
      out.write("        modal7.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event8) {\r\n");
      out.write("    if (event8.target == modal8) {\r\n");
      out.write("        modal8.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("window.onclick = function(event9) {\r\n");
      out.write("    if (event9.target == modal9) {\r\n");
      out.write("        modal9.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
