/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-23 06:17:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modaltest2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"ajaxFun0(v)\">\r\n");
      out.write(" <script src=\"https://d3js.org/d3.v3.min.js\"></script>\r\n");
      out.write("    <script src=\"https://rawgit.com/jasondavies/d3-cloud/master/build/d3.layout.cloud.js\" type=\"text/JavaScript\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("       function ajaxFun0(v){\r\n");
      out.write("\t\t\tvar xhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\txhttp.onreadystatechange = function() {\r\n");
      out.write("\t\t\t\tif (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("\t\t\t\t\t//응답된 데이터를 JSON 객체로 변환\r\n");
      out.write("\t\t\t\t\tdata = eval(this.responseText);\r\n");
      out.write("\t\t\t\t\t//wordcloud 그리는 함수의 parameter로 반영\r\n");
      out.write("\t\t\t\t\tdataView(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\txhttp.open(\"GET\", \"MainController?command=word&topic=\"+v, true);\r\n");
      out.write("\t\t\txhttp.send();\r\n");
      out.write("\t\t};\r\n");
      out.write("       \r\n");
      out.write("        var width = 1000, height = 500\r\n");
      out.write("\r\n");
      out.write("        var svg = d3.select(\"body\").append(\"svg\")\r\n");
      out.write("            .attr(\"width\", width)\r\n");
      out.write("            .attr(\"height\", height);\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         function dataView(data){//사용자 정의 함수\r\n");
      out.write("            showCloud(data);\r\n");
      out.write("            setInterval(function(){\r\n");
      out.write("                 showCloud(data)\r\n");
      out.write("            }, 5000) \r\n");
      out.write("         }\r\n");
      out.write("        \r\n");
      out.write("        wordScale = d3.scale.linear().domain([0, 100]).range([0, 150]).clamp(true);\r\n");
      out.write("        var svg = d3.select(\"svg\").append(\"g\").attr(\"transform\", \"translate(\" + width / 2 + \",\" + height / 2 + \")\");\r\n");
      out.write("\r\n");
      out.write("        function showCloud(data) {\r\n");
      out.write("            d3.layout.cloud().size([width, height])\r\n");
      out.write("                .words(data)\r\n");
      out.write("                .rotate(function (d) {\r\n");
      out.write("                    return d.text.length > 3 ? 0 : 0;\r\n");
      out.write("                })\r\n");
      out.write("                //스케일로 각 단어의 크기를 설정\r\n");
      out.write("                .fontSize(function (d) {\r\n");
      out.write("                    return wordScale(d.counting);\r\n");
      out.write("                })\r\n");
      out.write("                //클라우드 레이아웃을 초기화 > end이벤트 발생 > 연결된 함수 작동  \r\n");
      out.write("                .on(\"end\", draw)\r\n");
      out.write("                .start();\r\n");
      out.write("\r\n");
      out.write("            function draw(words) { \r\n");
      out.write("                var cloud = svg.selectAll(\"text\").data(words)\r\n");
      out.write("                //Entering words\r\n");
      out.write("                cloud.enter()\r\n");
      out.write("                    .append(\"text\")\r\n");
      out.write("                    .style(\"fill-opacity\", .5)\r\n");
      out.write("                    .attr(\"text-anchor\", \"middle\") \r\n");
      out.write("                    .attr('font-size', 1)\r\n");
      out.write("                    .text(function (d) {\r\n");
      out.write("                        return d.text;\r\n");
      out.write("                    }); \r\n");
      out.write("                cloud\r\n");
      out.write("                    .transition()\r\n");
      out.write("                    .duration(600)\r\n");
      out.write("                    .style(\"font-size\", function (d) {\r\n");
      out.write("                        return d.size + \"px\";\r\n");
      out.write("                    })\r\n");
      out.write("                    .attr(\"transform\", function (d) {\r\n");
      out.write("                        return \"translate(\" + [d.x, d.y] + \")rotate(\" + d.rotate + \")\";\r\n");
      out.write("                    })\r\n");
      out.write("                    .style(\"fill-opacity\", 1); \r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
